name = "scamledger-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
routes = [{ pattern = "api.scamledger.com", custom_domain = true }]

[vars]
ENVIRONMENT = "production"
FRONTEND_URL = "https://scamledger.com"
TURNSTILE_SECRET_KEY = ""
RP_ID = "scamledger.com"
RP_NAME = "ScamLedger"
RP_ORIGIN = "https://scamledger.com"

[[d1_databases]]
binding = "DB"
database_name = "cryptoscam-db"
database_id = "12b56ff3-d44a-4900-aa68-7cb3761baffd"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "KV"
id = "1377eed89ee1415daff5a466026869d8"
